### ISSUE TITLE
Glide4.0以上不能用

### ISSUE THREAD

**Issue by wapchief** [qdxxxx/BezierViewPager#7]
日志

 java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/Object;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com

**Comment by qdxxxx** [comment]
![这里写图片描述](http://img.blog.csdn.net/20171115212510519?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvcWlhbjUyMGFv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

可以先打开Project Structure,在你项目的Dependencise中将Glide的Scope改为Provided「模块私有」。

**Comment by qdxxxx** [comment]
已更新代码至 v1.0.7 , 具体使用方式移步  README.
