### ISSUE TITLE
I have a proguard error.

### ISSUE THREAD

**Issue by warrenth** [qdxxxx/BezierViewPager#9]
qdx.bezierviewpager_compile.vPage.CardPagerAdapter: can't find referenced method 'com.bumptech.glide.DrawableTypeRequest load(java.lang.Object)' in program class com.bumptech.glide.RequestManager

qdx.bezierviewpager_compile.vPage.CardPagerAdapter: can't find referenced class com.bumptech.glide.DrawableTypeRequest 

help me.

**Comment by qdxxxx** [comment]
Have sent an email for you , to Ask for more details , please check

**Comment by qdxxxx** [comment]
already Updated version to v1.0.7 , See the README.md for details .
